services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000" # Host:3000 → Contenedor:3000
    volumes:
      - ./project:/app # Sincroniza código local con el contenedor
      - /app/node_modules # Aísla dependencias
    command: ["pnpm", "run", "dev"]
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001" # Host:3001 → Contenedor:3001
    volumes:
      - ./Backend:/app # Sincroniza código local con el contenedor
      - /app/node_modules # Aísla dependencias
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_USER=myuser
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_PASSWORD=mypassword
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "mydatabase"]
      interval: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
